# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOCoAa0S12U_2By6KSHB7sou3J5N8-IZ

## Image Editing Tool with OpenCV and NumPy
"""

!pip install opencv-python matplotlib numpy

in, ymax = 200, 400
xmin, xmax = 200, 400


cropped_img = img_rgb[ymin:ymax, xmin:xmax]


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(cropped_img)
plt.title('Cropped Image (Face Only)')
plt.axis('off')

plt.show()

save_image(cropped_img, 'cropped_lena.jpg')

new_width = 200
new_height = 200
dimensions = (new_width, new_height)


resized_img = cv2.resize(img_rgb, dimensions)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title(f'Original Image {img_rgb.shape[:2]}')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(resized_img)
plt.title(f'Resized Image ({new_width}x{new_height})')
plt.axis('off')

plt.show()

save_image(resized_img, 'resized_lena.jpg')

gray_img = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Color Image')
plt.axis('off')


plt.subplot(1, 2, 2)

plt.imshow(gray_img, cmap='gray')
plt.title('Grayscale (B&W) Image')
plt.axis('off')

plt.show()

save_image(gray_img, 'gray_lena.jpg')

rotated_img = cv2.rotate(img_rgb, cv2.ROTATE_90_CLOCKWISE)


plt.figure(figsize=(10, 5))

# 1. Original Image (Seedhi)
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(rotated_img)
plt.title('Rotated Image (90° Clockwise)')
plt.axis('off')

plt.show()

save_image(rotated_img, 'rotated_lena.jpg')

blurred_img = cv2.GaussianBlur(img_rgb, (15, 15), 0)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Clean Image')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(blurred_img)
plt.title('Blurred Image (Smooth)')
plt.axis('off')

plt.show()

save_image(blurred_img, 'blurred_lena.jpg')

edges_img = cv2.Canny(img_rgb, 100, 200)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off')


plt.subplot(1, 2, 2)
# Edges hamesha single channel (black & white) hote hain, isliye cmap='gray' lagayenge
plt.imshow(edges_img, cmap='gray')
plt.title('Edge Detected (Canny)')
plt.axis('off')

plt.show()


save_image(edges_img, 'edges_lena.jpg')

alpha = 1.3
beta = 40


adjusted_img = cv2.convertScaleAbs(img_rgb, alpha=alpha, beta=beta)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(adjusted_img)
plt.title('Bright & High Contrast')
plt.axis('off')

plt.show()


save_image(adjusted_img, 'bright_lena.jpg')

watermarked_img = img_rgb.copy()

text = "AI Can"
position = (50, 480)
font = cv2.FONT_HERSHEY_SIMPLEX
font_scale = 1.5
color = (255, 255, 255)
thickness = 3


cv2.putText(watermarked_img, text, position, font, font_scale, color, thickness, cv2.LINE_AA)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(watermarked_img)
plt.title('Image with Text Watermark')
plt.axis('off')

plt.show()

save_image(watermarked_img, 'watermark_lena.jpg')

"""### 1. Read and Display Images"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Download a sample image from a more reliable source (OpenCV GitHub test image)
!wget -O sample_image.jpg https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg


image_path = 'sample_image.jpg'
img = cv2.imread(image_path)


if img is None:
    print(f"Error: Could not load image from {image_path}. Creating a dummy image instead.")

    img = np.zeros((300, 500, 3), dtype=np.uint8) + 255 # White image
    cv2.putText(img, "Image Not Loaded", (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
else:
    B
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


plt.figure(figsize=(10, 8))
plt.imshow(img_rgb)
plt.title('Original Image')
plt.axis('off') # Hide axes
plt.show()
print(f"Image loaded successfully. Shape: {img.shape}, Data type: {img.dtype}")

"""### 2. Save Images"""

def save_image(image, output_path):

    if len(image.shape) == 3 and image.shape[2] ==
        try:

            image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        except cv2.error:

            image_bgr = image
    else:
        image_bgr = image

    cv2.imwrite(output_path, image_bgr)
    print(f"Image saved successfully to {output_path}")


output_filename = 'saved_image.jpg'

save_image(img_rgb, output_filename)

files.download(output_filename)