# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ms4MB5w4R3NhDtYpvLt13lhia9RqPLXP
"""

import cv2 # OpenCV library for image processing
import numpy as np # NumPy for numerical operations, especially with image data

from google.colab.patches import cv2_imshow

def change_brightness_threshold(image_path):
    # Read the image
    img = cv2.imread(image_path)

    if img is None:
        print("Error: Image not found or could not be loaded.")
        return

    # Convert the image to grayscale
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


    thresh_value = 127  # You can adjust this value to control brightness/contrast
    max_value = 255
    _, thresholded_img = cv2.threshold(gray_img, thresh_value, max_value, cv2.THRESH_BINARY)

    cv2_imshow(img)
    cv2_imshow(thresholded_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


if __name__ == '__main__':
    try:

        print("Please upload an image file (e.g., 'image.jpg') to your Colab environment or provide its path.")
        print("Using a dummy image for now. For real usage, replace 'dummy_image.jpg' with your image file.")

        dummy_image = np.zeros((300, 500, 3), dtype=np.uint8)
        cv2.putText(dummy_image, 'Dummy Image', (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
        cv2.imwrite('dummy_image.jpg', dummy_image)

        change_brightness_threshold('dummy_image.jpg')
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please make sure you have an image file in your Colab environment or adjust the image_path.")

def remove_noise_filters(image_path):
    img = cv2.imread(image_path)

    if img is None:
        print("Error: Image not found or could not be loaded.")
        return


    cv2_imshow(img)


    Kernel size (ksize) is (5,5) - can be adjusted.
    blur_avg = cv2.blur(img, (5, 5))
    cv2_imshow(blur_avg)

    blur_gaussian = cv2.GaussianBlur(img, (5, 5), 0)
    cv2_imshow(blur_gaussian)


    blur_median = cv2.medianBlur(img, 5)
    cv2_imshow(blur_median)


    blur_bilateral = cv2.bilateralFilter(img, 9, 75, 75)
    cv2_imshow(blur_bilateral)

    print("Original Image, Average Blur, Gaussian Blur, Median Blur, and Bilateral Filtered Image displayed.")

if __name__ == '__main__':

        import os
        if not os.path.exists('dummy_image.jpg'):
            dummy_image = np.zeros((300, 500, 3), dtype=np.uint8)
            cv2.putText(dummy_image, 'Dummy Image', (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
            cv2.imwrite('dummy_image.jpg', dummy_image)

        remove_noise_filters('dummy_image.jpg')
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please make sure you have an image file in your Colab environment or adjust the image_path.")

def detect_edges(image_path):
    img = cv2.imread(image_path)

    if img is None:
        print("Error: Image not found or could not be loaded.")
        return

    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


    cv2_imshow(img)


    edges_canny = cv2.Canny(gray_img, 100, 200)
    cv2_imshow(edges_canny)


    dx=1, dy=0 detects vertical edges. dx=0, dy=1 detects horizontal edges.
    sobelx = cv2.Sobel(gray_img, cv2.CV_64F, 1, 0, ksize=5) # X-direction
    sobely = cv2.Sobel(gray_img, cv2.CV_64F, 0, 1, ksize=5) # Y-direction
    sobel_combined = cv2.magnitude(sobelx, sobely)
    cv2_imshow(sobel_combined.astype(np.uint8)) # Convert to uint8 for display


    laplacian = cv2.Laplacian(gray_img, cv2.CV_64F)
    cv2_imshow(np.uint8(np.absolute(laplacian))) # Convert to uint8 and absolute for display

    print("Original Image, Canny Edges, Sobel Edges (combined), and Laplacian Edges displayed.")


if __name__ == '__main__':
    try:

        import os
        if not os.path.exists('dummy_image.jpg'):
            dummy_image = np.zeros((300, 500, 3), dtype=np.uint8)
            cv2.putText(dummy_image, 'Dummy Image', (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
            cv2.imwrite('dummy_image.jpg', dummy_image)

        detect_edges('dummy_image.jpg')
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please make sure you have an image file in your Colab environment or adjust the image_path.")

def find_features(image_path):
    img = cv2.imread(image_path)

    if img is None:
        print("Error: Image not found or could not be loaded.")
        return


    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Display original image
    cv2_imshow(img)


    try:
        sift = cv2.SIFT_create()
        keypoints_sift, descriptors_sift = sift.detectAndCompute(gray_img, None)
        img_sift = cv2.drawKeypoints(gray_img, keypoints_sift, img.copy())
        cv2_imshow(img_sift)
        print(f"SIFT: Found {len(keypoints_sift)} keypoints.")
    except AttributeError:
        print("SIFT not found. This might be due to OpenCV version or build. Using ORB instead for now.")
    except Exception as e:
        print(f"An error occurred with SIFT: {e}")



    orb = cv2.ORB_create()
    keypoints_orb, descriptors_orb = orb.detectAndCompute(gray_img, None)
    img_orb = cv2.drawKeypoints(gray_img, keypoints_orb, img.copy(), color=(0, 255, 0), flags=0)
    cv2_imshow(img_orb)
    print(f"ORB: Found {len(keypoints_orb)} keypoints.")

    print("Original Image, SIFT Keypoints (if available), and ORB Keypoints displayed.")

if __name__ == '__main__':
    try:

        import os
        if not os.path.exists('dummy_image.jpg'):
            dummy_image = np.zeros((300, 500, 3), dtype=np.uint8)
            cv2.putText(dummy_image, 'Dummy Image', (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
            cv2.imwrite('dummy_image.jpg', dummy_image)

        find_features('dummy_image.jpg')
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please make sure you have an image file in your Colab environment or adjust the image_path.")

def create_panorama(image_paths):
    if len(image_paths) < 2:
        print("Please provide at least two images to create a panorama.")
        return


    images = []
    for path in image_paths:
        img = cv2.imread(path)
        if img is None:
            print(f"Error: Image not found or could not be loaded: {path}")
            return
        images.append(img)

    try:
        feature_detector = cv2.SIFT_create()
    except AttributeError:
        print("SIFT not found. Using ORB for feature detection.")
        feature_detector = cv2.ORB_create(nfeatures=5000)

    bf = cv2.BFMatcher()


    stitched_image = images[0]

    for i in range(len(images) - 1):

        img1 = stitched_image
        img2 = images[i+1]


        gray_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
        gray_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)


        kp1, des1 = feature_detector.detectAndCompute(gray_img1, None)
        kp2, des2 = feature_detector.detectAndCompute(gray_img2, None)

        if des1 is None or len(kp1) < 4 or des2 is None or len(kp2) < 4: # Need at least 4 points for homography
            print(f"Not enough features detected in image pair {i} and {i+1}. Skipping or returning.")
            return


        matches = bf.knnMatch(des1, des2, k=2)

        good_matches = []
        for m, n in matches:
            if m.distance < 0.75 * n.distance:
                good_matches.append(m)

        if len(good_matches) > 4:

            src_pts = np.float32([kp1[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
            dst_pts = np.float32([kp2[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)


            H, _ = cv2.findHomography(dst_pts, src_pts, cv2.RANSAC, 5.0)

            if H is not None:
                h1, w1 = img1.shape[:2]
                h2, w2 = img2.shape[:2]

                Get corners of img1 (already in its coordinate system, top-left is 0,0)
                corners_img1 = np.float32([[0, 0], [w1, 0], [w1, h1], [0, h1]]).reshape(-1, 1, 2)
                Get transformed corners of img2 (in img1's coordinate system using H)
                corners_img2 = np.float32([[0, 0], [w2, 0], [w2, h2], [0, h2]]).reshape(-1, 1, 2)
                transformed_corners_img2 = cv2.perspectiveTransform(corners_img2, H)


                all_corners = np.concatenate((corners_img1, transformed_corners_img2), axis=0)

                xmin, ymin = np.int32(all_corners.min(axis=0).ravel() - 0.5)
                xmax, ymax = np.int32(all_corners.max(axis=0).ravel() + 0.5)


                result_width = xmax - xmin
                result_height = ymax - ymin

                translation_matrix = np.array([[1, 0, -xmin], [0, 1, -ymin], [0, 0, 1]], dtype=np.float32)


                output_panorama = np.zeros((result_height, result_width, 3), dtype=np.uint8)

                warped_img1 = cv2.warpPerspective(img1, translation_matrix, (result_width, result_height))


                warped_img2 = cv2.warpPerspective(img2, translation_matrix @ H, (result_width, result_height))

                output_panorama = warped_img1.copy()

                mask = np.any(warped_img2 > 0, axis=-1)
                output_panorama[mask] = warped_img2[mask]

                stitched_image = output_panorama

            else:
                print(f"Homography not found for image pair {i} and {i+1}. Cannot stitch.")
                return
        else:
            print(f"Not enough good matches ({len(good_matches)}) found for image pair {i} and {i+1}. Cannot stitch.")
            return

    print("Panorama created!")
    cv2_imshow(stitched_image)


if __name__ == '__main__':
    try:

        img_left = np.zeros((300, 400, 3), dtype=np.uint8)
        cv2.rectangle(img_left, (50, 50), (350, 250), (255, 0, 0), -1) # Blue rectangle
        cv2.putText(img_left, 'Left Image', (100, 150), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
        cv2.imwrite('dummy_left.jpg', img_left)

        img_right = np.zeros((300, 400, 3), dtype=np.uint8)
        cv2.rectangle(img_right, (100, 50), (350, 250), (0, 255, 0), -1) # Green rectangle (with overlap)
        cv2.putText(img_right, 'Right Image', (150, 150), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
        cv2.imwrite('dummy_right.jpg', img_right)

        print("Created 'dummy_left.jpg' and 'dummy_right.jpg'. Attempting to stitch them...")
        create_panorama(['dummy_left.jpg', 'dummy_right.jpg'])

    except Exception as e:
        print(f"An error occurred during panorama creation: {e}")
        print("Please make sure you have the necessary image files or adjust the image_paths.")